project:
  type: website
  output-dir: docs

website:
  title: "Ashlyn Johnson"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: vapor
    css: styles.css
    toc: true

editor: visual

