project:
  type: website
  output-dir: docs

website:
  title: "wetware//software//data"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - blog.qmd
      - tt_blog.qmd
      - icon: github
        href: https://github.com/ashlyngjohnson
      - icon: twitter
        href: https://twitter.com/ashgjoh

format:
  html:
    theme: solar
    css: styles.css
    toc: true

editor: visual

