project:
  type: website
  output-dir: docs

website:
  title: "wetware//software//data"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - blog.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com

format:
  html:
    theme: cyborg
    css: styles.css
    toc: true

editor: visual

