---
title: "About Me"
---

My name is Ashlyn Johnson and I am an **aspiring data professional**.

By day, I study the role of astrocytes in frontotemporal dementia associated with tau pathology - with a particular interest in the astrocyte endfoot. I combine classical biochemical techniques with proteomic and transcriptomic approaches to dissect the impact of mutant tau on the gliovascular unit. Through this project, I've discovered a passion for data visualization and R programming.

By night, I'm bolstering my data skills. My time in graduate school has taught me that the parts of research that I enjoy most are the data analysis and visualization with R. I am happiest when I get to tinker with code in order to make the perfect graph. Thus, I've decided to broaden my data skill set by continuing to advance in R as well as to learn SQL and python.

After graduation, I hope to leverage both my scientific background and my data-related skills as a data professional. Earning a PhD comes with a unique set of skills that involve learning how to ask good questions, designing experiments or processes to answer those questions, and learning how to think critically about results and their impact on the field. These skills can be applied to any industry and will help me to excel in data-related tasks and goals.

#### Education

**B.S. Biological Sciences, North Carolina State University, 2017**

-   Concentration: Integrative Physiology and Neurobiology

-   Minors: Cognitive Science and Biotechnology

**Ph.D. Neuroscience, Emory University, In Progress**

-   Adviser: Dr. Chad Hales MD, PhD

-   [Publications](https://scholar.google.com/citations?user=p6HJwcMAAAAJ&hl=en)

**Certificates**

-   Google Data Analytics Certificate (4/8 courses completed)
